In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array1.shape

(9,)

In [5]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
type(array2)

numpy.ndarray

In [7]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
array2.shape

(3, 4)

ndarray 는 n dimensional array의 준말

In [9]:
array1.size

9

In [10]:
array2.size

12

In [11]:
numpy3 = np.full(3, 7)
numpy4 = np.zeros(4, dtype=int)
numpy5 = np.ones(5, dtype = int)
print(numpy3)
print(numpy4)
print(numpy5)

[7 7 7]
[0 0 0 0]
[1 1 1 1 1]


In [12]:
array6 = np.random.random(7)
print(array6)

[0.8206828  0.0713555  0.18453932 0.3921858  0.82900978 0.94026128
 0.42044649]


In [13]:
array7 = np.arange(7)
print(array7)
array8 = np.arange(3, 9)
print(array8)
array9 = np.arange(1, 40, 5)
print(array9)

[0 1 2 3 4 5 6]
[3 4 5 6 7 8]
[ 1  6 11 16 21 26 31 36]


In [14]:
array10 = np.arange(10)
print(array10)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
print(array10[[1, 3, 4]])

[1 3 4]


In [16]:
array11 = [2, 1, 3]
print(array10[array11])
print(array10[2:7])
print(array10[1:8:2])

[2 1 3]
[2 3 4 5 6]
[1 3 5 7]


In [17]:
array1 = np.arange(10)
array2 = np.arange(10, 20)
    
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [24]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [ ]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.

# 정답 출력
won_array